name: Release Binaries

on:
  release:
    types: [created]

jobs:
  build:
    name: Build ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
            target: x86_64-unknown-linux-gnu
            output: soundcloud-sync-linux-amd64
          - os: ubuntu-latest
            arch: arm64
            target: aarch64-unknown-linux-gnu
            output: soundcloud-sync-linux-arm64
          - os: windows-latest
            arch: amd64
            target: x86_64-pc-windows-msvc
            output: soundcloud-sync-windows-amd64.exe
          - os: macos-latest
            arch: amd64
            target: x86_64-apple-darwin
            output: soundcloud-sync-macos-amd64
          - os: macos-latest
            arch: arm64
            target: aarch64-apple-darwin
            output: soundcloud-sync-macos-arm64

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build binary
        run: deno compile --allow-net --allow-read --allow-write --allow-env --allow-sys --target ${{ matrix.target }} --output ${{ matrix.output }} src/cli.ts

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.output }}
          asset_name: ${{ matrix.output }}
          tag: ${{ github.ref }}
