name: Release Binaries

on:
  release:
    types: [created]

jobs:
  build:
    name: Build ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
            target: bun-linux-x64
            output: soundcloud-sync-linux-amd64
          - os: ubuntu-latest
            arch: arm64
            target: bun-linux-arm64
            output: soundcloud-sync-linux-arm64
          - os: windows-latest
            arch: amd64
            target: bun-windows-x64
            output: soundcloud-sync-windows-amd64.exe
          - os: macos-latest
            arch: amd64
            target: bun-darwin-x64
            output: soundcloud-sync-macos-amd64
          - os: macos-latest
            arch: arm64
            target: bun-darwin-arm64
            output: soundcloud-sync-macos-arm64

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build binary
        run: bun build --compile --target ${{ matrix.target }} --outfile ${{ matrix.output }} src/cli.ts

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.output }}
          asset_name: ${{ matrix.output }}
          tag: ${{ github.ref }}
